# Generated by Django 5.1.5 on 2025-06-03 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Current_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.client')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='current',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.current_reservation'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.client')),
            ],
        ),
        migrations.AddField(
            model_name='current_reservation',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.employee'),
        ),
        migrations.CreateModel(
            name='Past_reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.employee')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='past',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reserve.past_reservation'),
        ),
    ]
