# Generated by Django 5.1.5 on 2025-07-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_current_reservation_canceled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_reservation',
            name='notified_1h',
            field=models.BooleanField(default=False),#type: ignore
        ),
        migrations.AddField(
            model_name='current_reservation',
            name='notified_24h',
            field=models.BooleanField(default=False),#type: ignore
        ),
    ]
