# Generated by Django 5.2.4 on 2025-07-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_current_reservation_notified_1h_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
