# Generated by Django 5.2.4 on 2025-07-28 11:35

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_company_remove_employee_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': '予約', 'verbose_name_plural': '予約'},
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='notified_1h',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='notified_24h',
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder_1h', '1時間前リマインド'), ('reminder_24h', '24時間前リマインド'), ('custom', 'カスタム')], max_length=20, verbose_name='通知タイム')),
                ('sent_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='送信日時')),
                ('status', models.CharField(choices=[('pending', '未送信'), ('sent', '送信済み'), ('failed', '送信失敗')], default='pending', max_length=20, verbose_name='送信状態')),
                ('error_message', models.TextField(blank=True, verbose_name='エラーメッセージ')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_logs', to='reserve.reservation')),
            ],
            options={
                'verbose_name': '通知履歴',
                'verbose_name_plural': '通知ログ',
                'ordering': ['-sent_at'],
                'unique_together': {('reservation', 'notification_type')},
            },
        ),
        migrations.CreateModel(
            name='ReminderSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder_1h', '1時間前リマインド'), ('reminder_24h', '24時間前リマインド'), ('custom', 'カスタム')], max_length=20, verbose_name='通知タイム')),
                ('enabled', models.BooleanField(default=True, verbose_name='有効')),
                ('custom_hours', models.IntegerField(blank=True, help_text='カスタム時間を設定してください。', null=True, verbose_name='カスタム時間（時間）')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to='reserve.profile')),
            ],
            options={
                'verbose_name': 'リマインド設定',
                'verbose_name_plural': 'リマインド設定',
                'unique_together': {('profile', 'notification_type')},
            },
        ),
    ]
