# Generated by Django 5.1.5 on 2025-07-09 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_client_age_client_exsistence_current_reservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='mail',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
