# Generated by Django 5.1.5 on 2025-07-10 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0003_alter_client_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='current_reservation',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='current_reservation',
            name='is_canceled',
            field=models.BooleanField(default=False),#type: ignore
        ),
    ]
