# Generated by Django 5.2.4 on 2025-07-25 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_client_is_admin'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='employee',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='current_reservation',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='current_reservation',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='past_reservation',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_number',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.company'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.BooleanField(choices=[(True, '男性'), (False, '女性')])),
                ('age', models.IntegerField()),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reserve.company')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('purpose', models.CharField(max_length=200)),
                ('is_canceled', models.BooleanField(default=False)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('notified_1h', models.BooleanField(default=False)),
                ('notified_24h', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reserve.profile')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reserve.employee')),
            ],
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Current_reservation',
        ),
        migrations.DeleteModel(
            name='Past_reservation',
        ),
    ]
